### ISSUE TITLE
setLanguage ShipmentDetails enumbounds issue

### ISSUE THREAD

**Issue by WeTurkstra** [best-brands/bol-com-retailer-api#2]
This morning i got messages form my application failing due to the enumbounds check in the setLanguage function in the ShipmentDetails class. It gets the value "nl-NL" this is not in the bounds. 

I tried to find any changes in the documentation but couldn't find it!

To fix it i added nl-NL to the checkBounds function in the ShipmentDetails class.

Have you encountered this as wel??

**Comment by harm-smits** [comment]
What version are you using? I assume V4?

**Comment by harm-smits** [comment]
Yes I encountered this too. Also, this is an interesting point you are bringing up, I had the same errors, seems bol.com broke their ~~shitty~~ api again.

**Comment by harm-smits** [comment]
![image](https://user-images.githubusercontent.com/42849121/119098781-80547e80-ba16-11eb-818b-9b2af5995966.png)

They don't even adhere to their own specification 😭

**Comment by harm-smits** [comment]
I changed the behavior. I will likely get rid of enumerables all together in v5 seeing that they are changing them for no reason. https://github.com/best-brands/bol-com-retailer-api/commit/ec59e068369a89dc34e9ca6b4f52ba487248566a

**Comment by harm-smits** [comment]
For the record, I am making some time now to update the API to V5 in its entirety, after that I get to manually copy orders :/

**Comment by harm-smits** [comment]
This is done, feel free to update. Let me know if my tests missed anything.
