### ISSUE TITLE
Billingdetails missing in orders

### ISSUE THREAD

**Issue by WeTurkstra** [best-brands/bol-com-retailer-api#3]
Hey,

I seem to missing billings details in all the orders i fetch. Do you experience the same?
Is this another BOL.com mistake?

Thanks.

**Comment by harm-smits** [comment]
I have no idea, can you check how old your order is?

**Comment by WeTurkstra** [comment]
All the orders are from today. I used postman to call the api directly and it seems like the billingDetails are completly missing. 

Its a bit like the other issue we had a few weeks ago.

**Comment by harm-smits** [comment]
They changed it again indeed -_-

**Comment by WeTurkstra** [comment]
Great... hahaha. I love it when stuff randomly change. Our customers love it too😂.

Well i will make a workaround for it.

**Comment by harm-smits** [comment]
Great, I am currently not in the office so please let me know what exactly you change so I can merge it accordingly. Especially interested in the change in raw response.

This is becoming quite the nuisance :/

**Comment by WeTurkstra** [comment]
Yes ideed. Waht is will do is use the shipping Details for the billing details. I dont think its wise to do this in this repository.

There is no real way to fetch the billing details right now as far as i can see.

**Comment by harm-smits** [comment]
https://twitter.com/bol_com/status/1400398349761748993?s=19

**Comment by harm-smits** [comment]
Well, it's not a bug technically, since in the spec they define this as 'optional'. But it's needed for VAT invoices regardless.

**Comment by WeTurkstra** [comment]
Yea. I saw your tweet earlier and retweeted it. So it looks like a technical issue on their side?

**Comment by harm-smits** [comment]
Yep, no clue when it will be resolved though :(

**Comment by WeTurkstra** [comment]
I looks like the orders are coming through right now.
It might be fixed!

**Comment by harm-smits** [comment]
Yep, same here. I don't know why they don't test new deployments tbh. It scares me and I don't like it.

**Comment by harm-smits** [comment]
Seeing as this has been resolved by bol.com, I am going to close this issue.
